color: null
fieldLayouts:
  d5990062-69a0-42c5-9a4c-bb0ce80af62c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d4352875-b9d5-4e87-b2f5-b81818a49e11
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d9dfbb2-88b3-4274-9762-69c856f6b518 # Preview Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 219e4e38-ca5d-4c62-baee-bb026c66ea73
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e0a5b0bf-73f0-4e8e-822e-b4ea0bda99d5 # Text
            handle: previewText
            includeInCards: false
            instructions: null
            label: 'Preview Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f346633e-2034-4bc5-a2d4-806319253dde
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17ca4dbc-4eb7-46aa-a6e1-8840b78efb7c # Datetime
            handle: startDate
            includeInCards: false
            instructions: null
            label: 'Start Date'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e2be956-cb2c-4e6d-b867-36347fa69054
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1908e08e-4715-4582-981a-ae20b88e9b7c # Months
            handle: featuredMonths
            includeInCards: false
            instructions: 'Which months should this activity be displayed on the homepage'
            label: 'Featured Months'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd14b753-25a8-4377-b5c8-33efeddac53e
            userCondition: null
            warning: null
            width: 100
        name: Preview
        uid: 905db5e8-6896-47db-82f5-79e6b1564029
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e0a5b0bf-73f0-4e8e-822e-b4ea0bda99d5 # Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5debe6b-04d4-468f-98bf-29d97c01f2d5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e665c259-b527-4c5a-a7a3-e3ffb6498f27 # Image
            handle: heroImage
            includeInCards: false
            instructions: null
            label: 'Hero Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71631514-e575-46f1-a301-a3800772ceb0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6f19cee3-1de8-4684-852b-f59cfdf23892 # CTA
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf1151ba-c3fd-4c98-9d02-1d992b718e1d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b65b30fd-2906-4a3c-a08e-76954a4942ed # Overview
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1278e400-41a9-423a-bd80-47d2bd5cac9e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2efcdd43-3927-46bc-aab7-7d1576e97e29 # Announcements
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f0bd293-36f6-41d1-8a5a-6c6bd409a6a2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c9574e28-8586-4710-b9cd-a32663a53be6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c949c1b6-9b7b-4bbf-b3de-5fff9dd54c0d # Activity Modules
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0829098c-8242-40bb-8529-dc411831875e
            userCondition: null
            warning: null
            width: 100
        name: Modules
        uid: 7bba087f-d673-4cad-bcfa-0859660504f4
        userCondition: null
handle: activity
hasTitleField: true
icon: calendar-days
name: Activity
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
