color: null
fieldLayouts:
  65e74ab2-ac1f-4733-bec2-3f6cbe7fe90c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: db6d2b64-cbb4-41b7-9464-b7f19a51f60c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5d2512ec-b6a8-4f46-afbe-690d4e8f33f1
        userCondition: null
handle: blog
hasTitleField: true
icon: newspaper
name: Blog
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
