color: null
fieldLayouts:
  bd3eee68-7d5a-4b58-9edb-d572fc2ab7a3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f3f3b1c8-ae51-4d8b-8e09-e3402ee07273
            userCondition:
              class: craft\elements\conditions\users\UserCondition
              conditionRules:
                -
                  class: craft\elements\conditions\users\AdminConditionRule
                  uid: 04f3ca3b-0e06-4fde-ad71-dfa11fc3bfdf
                  value: true
              elementType: craft\elements\User
              fieldContext: global
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e0a5b0bf-73f0-4e8e-822e-b4ea0bda99d5 # Text
            handle: previewText
            includeInCards: false
            instructions: null
            label: 'Preview Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50bf35d0-1143-423b-9ce2-5f2f52e28bc8
            userCondition:
              class: craft\elements\conditions\users\UserCondition
              conditionRules:
                -
                  class: craft\elements\conditions\users\AdminConditionRule
                  uid: 8c2d627e-ef9c-436c-b115-a9cd78dc8960
                  value: true
              elementType: craft\elements\User
              fieldContext: global
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e36cf20a-eb0d-4de9-8a98-9f74d2ad0e15 # Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67b9fbeb-efba-4963-b624-2d02ab6ba52c
            userCondition:
              class: craft\elements\conditions\users\UserCondition
              conditionRules:
                -
                  class: craft\elements\conditions\users\AdminConditionRule
                  uid: 83fc7eb2-557f-430b-8b76-e203d20eb6c4
                  value: true
              elementType: craft\elements\User
              fieldContext: global
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e0a5b0bf-73f0-4e8e-822e-b4ea0bda99d5 # Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2bc596f-322b-4971-827f-c4f0bccd5433
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e665c259-b527-4c5a-a7a3-e3ffb6498f27 # Image
            handle: heroImage
            includeInCards: false
            instructions: null
            label: 'Hero Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfc3de6b-93da-4bd6-8da0-fbec9f374d05
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b65b30fd-2906-4a3c-a08e-76954a4942ed # Overview
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f0701ba-91fc-47c8-9da6-48133ec7963a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 21845b92-9016-4975-ad69-346de1c7a9a8 # Details
            handle: resources
            includeInCards: false
            instructions: null
            label: Resources
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bae1435-4c4e-4157-91cc-ae70c3302452
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2efcdd43-3927-46bc-aab7-7d1576e97e29 # Announcements
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94e8a731-68ca-4b20-8391-42bc511ededd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 87c7eb6f-29f4-4836-8740-ee6965ccb886 # Posts
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82d6f54d-e1c1-4864-a43e-13bc30a4a3ef
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: f2609bcc-2cf8-4ae9-92f2-27cb50c45b11 # Post
            handle: featuredPost
            includeInCards: false
            instructions: 'Select a post from your class to feature on the homepage.'
            label: 'Featured Post'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 036d8768-582a-4443-aabc-511acedb2d73
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 413ac764-83b7-4cae-b74a-78a257d50b79
        userCondition: null
handle: class
hasTitleField: true
icon: apple-whole
name: Class
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
