color: null
fieldLayouts:
  43ad935a-4ef5-4a20-870f-bada560e7f69:
    cardView:
      - 'layoutElement:481bedf3-aa5d-4c39-a5a8-8c46991ac2e1'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-03T01:18:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b2550555-deb3-4f7e-b654-8d42418ca8aa
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-03T01:26:43+00:00'
            elementCondition: null
            fieldUid: d623851d-e774-4508-a573-906ce42ac7c2 # Document
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 481bedf3-aa5d-4c39-a5a8-8c46991ac2e1
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: c5c6f1d9-930a-46f3-86a2-17bd512b83c1
        userCondition: null
handle: downloadCta
hasTitleField: true
icon: arrow-down
name: 'Download CTA'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
