color: null
fieldLayouts:
  0055c8cd-ce41-4819-9220-692d39a2cc48:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 03cc021d-395c-4661-9727-cbbefa6fbbcd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e0a5b0bf-73f0-4e8e-822e-b4ea0bda99d5 # Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6eeb6d5f-bd3b-49b0-a78a-f8a24802c5e8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e0a5b0bf-73f0-4e8e-822e-b4ea0bda99d5 # Text
            handle: subheading
            includeInCards: false
            instructions: null
            label: Subheading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7fccc764-7993-4ad8-8761-7c0bda90db65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b65b30fd-2906-4a3c-a08e-76954a4942ed # Overview
            handle: body
            includeInCards: false
            instructions: null
            label: Body
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f51954e7-6ab5-491e-8574-1a7cb20afa5f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e36cf20a-eb0d-4de9-8a98-9f74d2ad0e15 # Color
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5a714a7-8694-45c8-bb67-41cf082c09da
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7607fe98-a832-439e-a95e-72fb10fc6452
        userCondition: null
handle: intro
hasTitleField: false
icon: text
name: Intro
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
