color: null
fieldLayouts:
  366d7087-9667-4a1c-af38-1515706bed90:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-16T00:29:02+00:00'
            elementCondition: null
            fieldUid: e0a5b0bf-73f0-4e8e-822e-b4ea0bda99d5 # Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 127eaea2-011b-4751-82d7-3ec9a6d1e331
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-16T00:29:02+00:00'
            elementCondition: null
            fieldUid: e665c259-b527-4c5a-a7a3-e3ffb6498f27 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: 'Media Item'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c484629b-bb48-4f4c-ab9c-bdb83743513f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-16T00:30:14+00:00'
            elementCondition: null
            fieldUid: 188ef9dd-6d05-4bc5-89da-6206d1873457 # Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf4e00b9-ccf9-4b63-a26b-3802682e8f81
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 2ce26a3b-2e25-498b-8715-af219a9cb2d7
        userCondition: null
handle: media
hasTitleField: false
icon: image
name: Media
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
