color: null
fieldLayouts:
  d0127bed-fbd9-4d87-aa29-376f05656695:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 27aeb37d-0bcf-492a-8bc3-c28b10fafc36
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b8a6904-ae52-4971-b1ff-e099fa19bfb4 # Preview Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c91ef1c0-7ea9-426a-b5a5-35779ed782ff
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e0a5b0bf-73f0-4e8e-822e-b4ea0bda99d5 # Preview Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3eec01eb-7506-4c32-bbba-a2ee61deb6fa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3a2d0940-71c4-4c49-8ccf-01022eba3b31
        userCondition: null
handle: page
hasTitleField: true
icon: memo
name: Page
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
