color: null
fieldLayouts:
  2df94150-0425-4804-8899-5d85094cb6df:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 46521eb7-539e-4b62-bead-513e273dc250
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17ca4dbc-4eb7-46aa-a6e1-8840b78efb7c # Datetime
            handle: startDate
            includeInCards: false
            instructions: null
            label: 'Start Date'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7755f22c-04ed-4a5d-8018-67e4f8bc2cb2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a9f36339-edb8-49a5-889e-3545779d1794 # Activity
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed2f31db-f2c3-498e-9a3b-b23b3967c137
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e0a5b0bf-73f0-4e8e-822e-b4ea0bda99d5 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8accd9ad-7186-4728-ac3c-4747057bd9af
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 6f19cee3-1de8-4684-852b-f59cfdf23892 # CTA
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50b86e24-a2a8-4ae1-b34d-2109fe49096f
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 474bf09e-64a3-4405-a80a-0fb1bf7c7e3a
        userCondition: null
handle: reminder
hasTitleField: true
icon: bell
name: Reminder
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
