color: null
fieldLayouts:
  2df94150-0425-4804-8899-5d85094cb6df:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 46521eb7-539e-4b62-bead-513e273dc250
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b8a6904-ae52-4971-b1ff-e099fa19bfb4 # Preview Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ab5cdc9-2009-4ad1-9025-1eb6cbafb7b8
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e0a5b0bf-73f0-4e8e-822e-b4ea0bda99d5 # Preview Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc636e34-6579-4378-a9a3-9d625694f7b2
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: b65b30fd-2906-4a3c-a08e-76954a4942ed # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71534837-38a2-4892-b1ff-c5932e0d54c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6f19cee3-1de8-4684-852b-f59cfdf23892 # CTA
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50b86e24-a2a8-4ae1-b34d-2109fe49096f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 474bf09e-64a3-4405-a80a-0fb1bf7c7e3a
        userCondition: null
handle: reminder
hasTitleField: true
icon: bell
name: Reminder
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
