color: null
fieldLayouts:
  a586ab72-cb3a-4a91-894f-81b981eb6ac9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6ce38a39-c46b-4dd1-8c99-d67ace1efa1f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b65b30fd-2906-4a3c-a08e-76954a4942ed # Overview
            handle: details
            includeInCards: false
            instructions: null
            label: Details
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8aebe5fc-bac3-41ec-87dd-1a1b573e532f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9cb11a30-840e-4778-ac4e-d560ae4b70ce # Subject
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4981c9b-e8bb-4a29-9a15-eb4be44de54d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 938bdfab-80e2-4116-9e3d-66d94c36376f # Classes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56169235-ed44-4fb3-97bb-c72746a5fdbc
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: aefc2ea7-d4f5-41af-be16-dabf090f634d
        userCondition: null
handle: subjectUpdate
hasTitleField: true
icon: bullhorn
name: 'Subject Update'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
