headingLevels: false
name: 'Simple Plus'
options:
  link:
    decorators:
      isExternal:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in new tab'
        mode: manual
toolbar:
  - bold
  - italic
  - link
  - subscript
  - superscript
  - bulletedList
  - numberedList
