altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  6d60bb05-b55b-4a9a-9cdb-d324a533afa1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b1714819-e93e-4766-a879-099a569c807a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4591475f-508e-4e5a-bf8f-074ff81032d6
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
