columnSuffix: null
handle: activityModules
instructions: null
name: 'Activity Modules'
searchable: false
settings:
  createButtonLabel: 'New Module'
  entryTypes:
    - c56fb994-3459-4417-9f0f-0ce9f4359b70 # Accordion List
    - ae3e4e31-15a0-4883-9c22-01637617e803 # Card List
    - 93400719-64ce-46ce-996c-008e37c78a42 # Color Split
    - 1e6dc74f-eb75-4216-9fff-e9ca1d82313c # Intro
    - 36aa60ca-9dcf-435a-88fb-80d286f8cde5 # Media Split
    - 904d4a16-ab49-40f5-9519-53c814f59997 # Text List
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
