columnSuffix: null
handle: cards
instructions: null
name: Cards
searchable: false
settings:
  createButtonLabel: 'New Card'
  defaultIndexViewMode: cards
  entryTypes:
    - 731fd8e2-ca50-4fbb-b8b7-3a27ef8bf902 # Card
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
