columnSuffix: null
handle: coaches
instructions: null
name: Coaches
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a coach'
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedEntries: false
  showUnpermittedSections: false
  sources:
    - 'section:658d8481-cff5-4eb1-afe9-1a1288ea9b54' # Coaches
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list-inline
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
