columnSuffix: null
handle: color
instructions: null
name: Color
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Red
        -
          - value
          - red
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Orange
        -
          - value
          - orange
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Yellow
        -
          - value
          - yellow
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Green
        -
          - value
          - green
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Blue
        -
          - value
          - blue
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Indigo
        -
          - value
          - indigo
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Violet
        -
          - value
          - violet
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
