columnSuffix: null
handle: details
instructions: null
name: Details
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: fda357e6-6234-4a8c-843e-7c973f47e463 # Simple Plus
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
