columnSuffix: null
handle: details
instructions: null
name: Details
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  css: ".ck-content em.highlight {\r\n    background: rgba(255, 255, 0, 0.5);\r\n    font-style: normal;\r\n    font-weight: 600;\r\n}"
  cssFile: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  fullGraphqlData: false
  headingLevels: false
  js: null
  jsFile: null
  options:
    link:
      decorators:
        isExternal:
          attributes:
            rel: 'noopener noreferrer'
            target: _blank
          label: 'Open in new tab'
          mode: manual
    style:
      definitions:
        -
          classes:
            - highlight
          element: em
          name: Highlight
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  toolbar:
    - bold
    - italic
    - underline
    - link
    - subscript
    - superscript
    - bulletedList
    - numberedList
    - style
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
