columnSuffix: null
handle: gridSize
instructions: null
name: 'Grid Size'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - '2'
        -
          - value
          - '2'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3'
        -
          - value
          - '3'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '4'
        -
          - value
          - '4'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
