columnSuffix: null
handle: posts
instructions: null
name: Posts
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:de580ac3-ebc6-4ebd-af7e-6a39accf69f3' # Posts
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:96a1a8e5-308a-4f2e-b084-6b353e026e23' # Images
  restrictedLocationSubpath: null
  selectionLabel: 'Add a post'
  showCardsInGrid: false
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:de580ac3-ebc6-4ebd-af7e-6a39accf69f3' # Posts
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
