columnSuffix: null
handle: referenceUrl
instructions: null
name: 'Reference URL'
searchable: false
settings:
  maxLength: 500
  showLabelField: false
  showTargetField: false
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
