columnSuffix: null
handle: season
instructions: null
name: Season
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Fall
        -
          - value
          - fall
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Winter
        -
          - value
          - winter
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Spring
        -
          - value
          - spring
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Summer
        -
          - value
          - summer
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
