columnSuffix: null
handle: video
instructions: null
name: Video
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - video
  branchLimit: null
  defaultUploadLocationSource: 'volume:5482c96e-84ee-4297-9e2b-8ac82e183ec2' # Videos
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:96a1a8e5-308a-4f2e-b084-6b353e026e23' # Images
  restrictedLocationSubpath: null
  selectionLabel: 'Add a video'
  showCardsInGrid: false
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:5482c96e-84ee-4297-9e2b-8ac82e183ec2' # Videos
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
