dateModified: 1718825727
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:2d6cc29e-95ec-4121-a242-f74b9a1053a6' # Activities
      tableAttributes:
        - 'field:9d9dfbb2-88b3-4274-9762-69c856f6b518' # Preview Image
        - 'fieldInstance:fd14b753-25a8-4377-b5c8-33efeddac53e'
        - postDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:e14121b9-4e8c-49a4-afb6-d3a822d3b8ad' # Reminders
      tableAttributes:
        - 'field:e0a5b0bf-73f0-4e8e-822e-b4ea0bda99d5' # Text
        - 'fieldInstance:7755f22c-04ed-4a5d-8018-67e4f8bc2cb2'
        - 'field:a9f36339-edb8-49a5-889e-3545779d1794' # Activity
        - postDate
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:4d3180d1-ff38-4024-8d50-29f13c7391e6' # Classes
      tableAttributes:
        - 'field:88315e38-3bc8-4c3e-b756-311a3e6f8105' # Teacher
        - postDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:613dcfc9-5442-4f47-8d88-b634483e0d47' # Subject Updates
      tableAttributes:
        - 'field:9cb11a30-840e-4778-ac4e-d560ae4b70ce' # Subject
        - 'field:938bdfab-80e2-4116-9e3d-66d94c36376f' # Classes
        - postDate
        - authors
      type: native
    -
      key: 'section:478d6f7d-a53b-42eb-a9ce-671857c743a3' # Blog
      type: native
email:
  fromEmail: trevor@brasstacksweb.com
  fromName: 'Morganton Day School'
  replyToEmail: null
  template: null
  transportSettings:
    messageStream: ''
    token: $POSTMARK_API_KEY
  transportType: craftcms\postmark\Adapter
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@assetBasePath/images'
    type: craft\fs\Local
    url: '@assetBaseUrl/images'
meta:
  __names__:
    1aafc3c1-b10e-4134-b462-61acf0f69dcf: Months # Months
    1e8dde7a-23fd-40a2-805e-3e82c37fef0a: Class # Class
    2d6cc29e-95ec-4121-a242-f74b9a1053a6: Activities # Activities
    2efcdd43-3927-46bc-aab7-7d1576e97e29: Announcements # Announcements
    4d3180d1-ff38-4024-8d50-29f13c7391e6: Classes # Classes
    6f19cee3-1de8-4684-852b-f59cfdf23892: CTA # CTA
    7c331c3a-8fcf-4b9f-ad9e-c937ea0d6e1d: Page # Page
    9cb11a30-840e-4778-ac4e-d560ae4b70ce: Subject # Subject
    9d9dfbb2-88b3-4274-9762-69c856f6b518: 'Preview Image' # Preview Image
    17ca4dbc-4eb7-46aa-a6e1-8840b78efb7c: Datetime # Datetime
    019d8137-088c-4f8f-9662-d26ddd7f2fb7: 'Morganton Day School' # Morganton Day School
    87c7eb6f-29f4-4836-8740-ee6965ccb886: Posts # Posts
    88e145c4-1350-4e7c-bb88-a9a9233ebaf2: Announcement # Announcement
    96a1a8e5-308a-4f2e-b084-6b353e026e23: Images # Images
    462b813e-6582-4566-946a-0979bf81f1ca: Simple # Simple
    478d6f7d-a53b-42eb-a9ce-671857c743a3: Blog # Blog
    507c2c35-81fa-4361-90d7-f7514bbb4434: Activity # Activity
    613dcfc9-5442-4f47-8d88-b634483e0d47: 'Subject Updates' # Subject Updates
    666a2d7b-63a0-4256-acdd-fd5c0af0714f: Subjects # Subjects
    812fd012-9cc4-4c3c-bf03-845a6340a1f5: 'Morganton Day School' # Morganton Day School
    938bdfab-80e2-4116-9e3d-66d94c36376f: Classes # Classes
    1908e08e-4715-4582-981a-ae20b88e9b7c: Months # Months
    2757b28b-9302-44d3-8dcf-259f2c2fdf24: 'Page CTA' # Page CTA
    7459fa4e-33c3-4be0-8868-4011ce1be81e: Reminder # Reminder
    46092a2d-3811-4600-a2d4-856c6ce5b8cd: 'External CTA' # External CTA
    56004d8a-9fa9-41c8-b0db-eb75c8b2e22d: Default # Default
    88315e38-3bc8-4c3e-b756-311a3e6f8105: Teacher # Teacher
    a4fa5523-8cdd-400d-8f0e-50b8bd7c2802: 'Reference URL' # Reference URL
    a9f36339-edb8-49a5-889e-3545779d1794: Activity # Activity
    b65b30fd-2906-4a3c-a08e-76954a4942ed: Overview # Overview
    c105124b-b3d5-43c9-9079-0cd2196e25d3: Page # Page
    cbf5afdd-99f1-4d21-a978-952e00f4212b: 'Subject Update' # Subject Update
    dc10bcf2-6231-404f-8016-5f0e146e65a4: Teachers # Teachers
    de580ac3-ebc6-4ebd-af7e-6a39accf69f3: Posts # Posts
    e0a5b0bf-73f0-4e8e-822e-b4ea0bda99d5: Text # Text
    e36cf20a-eb0d-4de9-8a98-9f74d2ad0e15: Color # Color
    e665c259-b527-4c5a-a7a3-e3ffb6498f27: 'Hero Image' # Hero Image
    e14121b9-4e8c-49a4-afb6-d3a822d3b8ad: Reminders # Reminders
    ee745466-fccc-4f6b-90ba-7a293f18eb0c: Blog # Blog
    fd20c5e5-4c47-4c8c-af5b-ee45e71242b4: 'User Photos' # User Photos
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  postmark:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
system:
  edition: pro
  live: true
  name: 'Morganton Day School'
  retryDuration: null
  schemaVersion: 5.0.0.20
  timeZone: America/New_York
