fieldLayouts:
  f1cd68db-1a03-4227-a4e9-09ee52b4d4c1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-17T18:57:22+00:00'
            elementCondition: null
            fieldUid: e665c259-b527-4c5a-a7a3-e3ffb6498f27 # Image
            handle: logo
            instructions: null
            label: Logo
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 769501fa-95ca-401b-9c84-19841e4cd681
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-17T18:57:22+00:00'
            elementCondition: null
            fieldUid: cd8cda62-462c-44a7-90ff-4ab2495badca # Nav Links
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c40167d-2dbc-4642-8576-5b88c76ebd06
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-17T18:58:57+00:00'
            elementCondition: null
            fieldUid: e3999e4e-a947-4d65-8944-1f558463fe8f # Social Links
            handle: iconLinks
            instructions: null
            label: 'Icon Links'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ba9965b-cd0b-4a58-861f-95fb76d5b87f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-17T18:57:22+00:00'
            elementCondition: null
            fieldUid: 6f19cee3-1de8-4684-852b-f59cfdf23892 # CTA
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12d682b7-1920-490c-95e3-5a9809e79308
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 13553639-223b-4b02-a477-b16caa16b9b4
        userCondition: null
handle: header
name: Header
sortOrder: 1
