defaultPlacement: end
enableVersioning: true
entryTypes:
  - ee745466-fccc-4f6b-90ba-7a293f18eb0c # Blog
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  812fd012-9cc4-4c3c-bf03-845a6340a1f5: # Morganton Day School
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: 'blog/{slug}'
type: channel
