defaultPlacement: end
enableVersioning: true
entryTypes:
  - cceee7ec-12bf-4a50-8b29-d871bd33ae04 # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  812fd012-9cc4-4c3c-bf03-845a6340a1f5: # Morganton Day School Titan Link Parent Portal
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
