defaultPlacement: end
enableVersioning: true
entryTypes:
  - cbf5afdd-99f1-4d21-a978-952e00f4212b # Subject Update
handle: subjectUpdates
maxAuthors: 1
name: 'Subject Updates'
propagationMethod: all
siteSettings:
  812fd012-9cc4-4c3c-bf03-845a6340a1f5: # Morganton Day School
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
