defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ac7c177f-dba3-40b3-8ac3-182aa928a372 # Titan Fund Campaign
handle: titanFund
maxAuthors: 1
minAuthors: 1
name: 'Titan Fund'
propagationMethod: all
siteSettings:
  812fd012-9cc4-4c3c-bf03-845a6340a1f5: # Morganton Day School Titan Link Parent Portal
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
